[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
agentvault_solana = "7gURzVbrmtzJ8QoC9sC584fw9nkyahuUdFDmPnnCD6dB"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
