export type Task = {
  id: string;
  title: string;
  description: string;
  reward: string;
  minRep: number;
  tags?: string[];
  creatorAddress: string;
  agentId: string | null;
  agentAddress?: string | null;
  status: "open" | "assigned" | "in_progress" | "completed" | "paid";
  escrowAddress: string | null;
  escrowId: string | null;
  escrowStatus: "wallet_created" | "pending";
  escrowFundingTxId?: string | null;
  escrowFundingState?: "not_configured" | "submitted" | "error";
  escrowReleaseTxId?: string | null;
  escrowReleaseState?: "not_released" | "submitted" | "error" | "not_configured";
  ciphertext: string;
  createdAt: string;
  assignedAt?: string;
};
